### PR TITLE
Onboarding notifications

### PR DESCRIPTION
**Pull request by L8D**

### CODE REVIEW

**Comment by garrethdev** [comment]
@L8D  Getting an internal server error when I try and login into a new account

**Comment by L8D** [comment]
@GarrethDottin Forgot to run the new migrations, should be working now

**Comment by Ryan-Parker** [comment]
@L8D Just tested this out. Got an internal server error as well

**Comment by L8D** [comment]
@Ryan-Parker are you testing this with a new account or an existing one? I'm not getting any errors signing in through my existing account but I haven't tried signing in as a new user.

**Comment by Ryan-Parker** [comment]
@L8D I am getting the error when trying to sign in as a new user. My previously signed in accounts work fine.

**Comment by L8D** [comment]
@Ryan-Parker try now or in the next few minutes

**Comment by L8D** [comment]
@ZambiBambi if you run `gotrUser.save({introduced: false})` in a JS console it will reset the onboarding process.

**Comment by Ryan-Parker** [comment]
@L8D Just tested again and am still not able to login with a new google account.

**Comment by garrethdev** [comment]
@L8D @Ryan-Parker it works on Twitter try using a new account through there as we're not testing login in this branch.

**Comment by L8D** [comment]
@GarrethDottin the issue is related to the avatar substitution we're doing on the backend and has nothing to do with this branch actually

**Comment by garrethdev** [comment]
@L8D is Google sign up broken for all users? Not clear on what you're suggesting

**Comment by garrethdev** [comment]
@L8D When I created a new user through my google account the onboarding notifications didnt come  up but the initial task was loaded into the system. It worked however with a new user through twitter.

**Pull request merged**
