### PR TITLE
added NewsFeed Fade when Task in Session

### PR DESCRIPTION
**Pull request by garrethdev**

### CODE REVIEW

**Comment by Ryan-Parker** [comment]
@Arilas on first look of this PR the newsfeed layout is broken and I am not seeing the fade take effect. 

screen shot 2015-09-10 at 3 36 52 pm

**Comment by Ryan-Parker** [comment]
Hitting the reset timer button does not return the newsfeed to its original state with it not being faded and rotating again. 

screen shot 2015-09-11 at 6 36 37 am

**Comment by Arilas** [comment]
Fixed Reset Timer

**Comment by Ryan-Parker** [comment]
@Arilas The fade seems to work on system generated tasks, but for user generated tasks it does not. 

screen shot 2015-09-11 at 7 02 25 am

**Comment by Arilas** [comment]
Seems to be fixed.

**Comment by Ryan-Parker** [comment]
@Arilas I am no longer seeing the newsfeed "unfade" when I reset the timer or complete a task to return to its original state. 
screen shot 2015-09-11 at 11 08 41 am

**Pull request merged**
