### PR TITLE
Landing page updates

### LINKED ISSUE #124: Add Inspectlet Analytics
Login information for inspectlet should be in our account. Add to codebase so we can view how people interact with the social feed

### LINKED ISSUE #162: New Landing Page Designs
Designs should reflect the new landing page designs. Assets can be found in the google drive design folder. 

This includes the following: 
-New UI 
-New Fonts 
-New Copy for Panel 1, 2. and Social Panel. Copy in Google doc below.(https://docs.google.com/document/d/1bsLxIfwh0WZXLIW3_tTOndevAUlAiRMOfNZpSoUsdBM/edit#)
-The rest of the content will stay the same just need to implement the new skin 

copy of go_landing_0001_2

### PR DESCRIPTION
**Pull request by L8D**
closes #162 
closes #124

### CODE REVIEW

**Comment by Ryan-Parker** [comment]
@L8D Where would I be able to view the new landing page?

**Comment by L8D** [comment]
@Ryan-Parker I have setup heroku app-review deploys (removing the need for a staging server) for pull requests. You can find the server for this pull-request here: https://grooveotter-demo-pr-172.herokuapp.com/

**Comment by L8D** [comment]
@ZambiBambi I believe the branch is ready to be tested. You can find a live version running here: https://grooveotter-demo-pr-172.herokuapp.com/

**Comment by ZambiBambi** [comment]
Thanks @L8D

**Pull request merged**
