### PR TITLE
Mobile compatibility fixes

### PR DESCRIPTION
**Pull request by L8D**
This is only so I can get a live pr-review server and I can test through browserstack from there. This is not ready to merge

### CODE REVIEW

**Comment by Ryan-Parker** [comment]
sounds good @L8D thanks for the update

**Comment by L8D** [comment]
@Ryan-Parker Please try to load this site on mobile and let me know if the problem persists. I can't reproduce the errors through browserstack, so I'm assuming this fix works.

**Comment by Ryan-Parker** [comment]
@L8D I just tested on my device and the problem still persists. I am on an iPhone 6 using chrome & safari.

**Comment by L8D** [comment]
@Ryan-Parker Are you testing on grooveotter.com or https://grooveotter-demo-pr-239.herokuapp.com/ ?

**Comment by Ryan-Parker** [comment]
@L8D I was testing on 239 on my device. Can you try testing on a device instead of Browserstack?

**Pull request closed without merging**
