### PR TITLE
#245 fixed Like Button

### PR DESCRIPTION
**Pull request by Arilas**

### CODE REVIEW

**Comment by Arilas** [comment]
Depends on https://github.com/GrooveOtter/grooveotter-api/pull/23

**Comment by Ryan-Parker** [comment]
@Arilas I am not seeing the like button on system generated newsfeed items like the "first task of the day" 
screen shot 2015-09-10 at 3 39 45 pm

**Comment by Ryan-Parker** [comment]
@Arilas I am also not seeing the number change when I select the like button. The color changes but it does not add to the like count. 
screen shot 2015-09-10 at 3 43 49 pm

**Comment by GarrethDottin** [comment]
image

**Comment by garrethdev** [comment]
screen shot 2015-09-11 at 6 47 44 am

**Comment by Arilas** [comment]
Fixed Counter

**Comment by garrethdev** [comment]
This is what i'm seeing locally. So when I reload the page the second image shows but the first time it still has the issue. 

screen shot 2015-09-11 at 7 10 24 am

After Reloading Image:
screen shot 2015-09-11 at 7 10 39 am

**Comment by garrethdev** [comment]
@Arilas  Actually im seeing it working now

**Pull request merged**
